# Generated by Django 5.2.6 on 2025-09-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_news_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
