# Generated by Django 5.2.6 on 2025-10-01 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='id',
        ),
    ]
